# Generated by Django 4.1.3 on 2022-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish", name="description", field=models.TextField(),
        ),
    ]
